package laxer;

public enum NomeProducao {
	
	prodPrograma,
	prodClasse,
	prodDeclaraID,
	prodListaFuncao,
	prodListaFuncaoLinha,
	prodFuncao,
	prodFDID,
	prodListaArg,
	prodListaArgLinha,
	prodArg,
	prodRetorno,
	prodMain,
	prodTipoMacro,
	prodTipoMacroLinha,
	prodTipoPrimitivo,
	prodListaCmd,
	prodListaCmdLinha,
	prodCmd,
	prodCmdIf,
	prodCmdIfLinha,
	prodCmdWhile,
	prodCmdWrite,
	prodCmdWriteLn,
	prodCmdLinha,
	prodCmdDuasLinhas,
	prodCmdAtribuiLinha,
	prodFexp,
	prodFexp2,
	prodExpressao,
	prodExpressaoLinha,
	prodExpressao1,
	prodExpressao1Linha,
	prodExpressao2,
	prodExpressao2Linha,
	prodExpressao3,
	prodExpressao3Linha,
	prodExpressao4,
	prodExpressao4Linha,
	prodOpUnario;
	
}
